#!/usr/bin/env node
'use strict'

var cli = require('./dist'),
    minimist = require('minimist');

if (require.main === module) {
    var argv = (minimist)(process.argv.slice(2));

    if (argv._.length === 0) {
        console.log(cli.usage);
    }

    cli.cli(argv, function(err) {
        if (err) {
            console.error('ERROR: ' + err);
        }
    });
}
